# SPDX-License-Identifier: Apache-2.0

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-advanced-tools
PKG_VERSION:=1.0.1
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Codex

LUCI_TITLE:=Advanced Tools
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
LUCI_SUBMENU_FORCED:=none

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
